name: coverage
on: [pull_request]

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    name: Testing coverage action
    steps:
      - uses: actions/checkout@master
      - uses: Phil-Barber/python-coverage@master
