name: coverage
on: [pull_request]

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    name: Testing coverage action
    steps:
    - name: Test
      id: test
      uses: https://github.com/Phil-Barber/comment-on-pr@update-comment
