name: coverage
on: [pull_request]

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    name: Testing coverage action
    steps:
      - uses: actions/checkout@master
      - uses: Phil-Barber/comment-on-pr@update-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: template.md
          update-comment: coverage
