name: coverage
on: [pull_request]

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    name: Testing coverage action
    steps:
      - uses: actions/checkout@master
      - run: pip install coverage && coverage run && (coverage report > .github/workflows/coverage-report.md)
        shell: bash
      - uses: Phil-Barber/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: coverage-report.md
          updatecomment: coverage
